name: Test workflow
# on: [push, workflow_dispatch ]
on:
  push: [main]
  workflow_dispatch:

jobs:
  my-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code to the runner
        uses: actions/checkout@v3

      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Run test
      #   run: npm run test

  deploy:
    #This will ensure the job runs after test, instead of parallel
    needs: [my-tests]

    runs-on: ubuntu-latest

    steps:
      - name: Get code to the runner
        uses: actions/checkout@v3

      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: deploy

        run: echo "Deploying...."
