name: Test workflow
on: push

jobs:
  my-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code to the runner
        uses: actions.checkout@v3

      - name: Install Node jobs
        uses: checkout/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Run test
      #   run: npm run test
