name: Test workflow
# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - "dev-*" # dev-group, dev-tester-2024 etc
      - "feat/**" # feat/new, feat/new/chat-box etc
  workflow_dispatch:

jobs:
  my-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code to the runner
        uses: actions/checkout@v3

      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Run test
      #   run: npm run test

  deploy:
    #This will ensure the job runs after test, instead of parallel
    needs: [my-tests]

    runs-on: ubuntu-latest

    steps:
      - name: Get code to the runner
        uses: actions/checkout@v3

      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Build app
      - run: npm run build

      - name: deploy
        run: echo "Deploying...."

      - name: Save artifact/build folder
        uses: actions/upload-artifact
        with:
          name: dist-backup
          # path: .next
          path: |
            .next
            README.md
